// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetWorth.Data;

#nullable disable

namespace NetWorth.Data.Migrations
{
    [DbContext(typeof(NetWorthDbContext))]
    [Migration("20260808105213_AccountInstruments")]
    partial class AccountInstruments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetWorth.Data.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AccountId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountInstrument", b =>
                {
                    b.Property<Guid>("AccountInstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountInstrumentId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("AccountId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("AccountInstruments");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountInstrumentSnapshot", b =>
                {
                    b.Property<Guid>("AccountInstrumentSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountInstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountInstrumentSnapshotId");

                    b.HasIndex("AccountInstrumentId");

                    b.HasIndex("AccountSnapshotId", "AccountInstrumentId")
                        .IsUnique();

                    b.ToTable("AccountInstrumentSnapshots");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountSnapshot", b =>
                {
                    b.Property<Guid>("AccountSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("AccountSnapshotId");

                    b.HasIndex("AccountId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("AccountSnapshots");
                });

            modelBuilder.Entity("NetWorth.Data.Models.Institution", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("NetWorth.Data.Models.Instrument", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ticker")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("InstrumentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasFilter("[Ticker] IS NOT NULL");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("NetWorth.Data.Models.Account", b =>
                {
                    b.HasOne("NetWorth.Data.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountInstrument", b =>
                {
                    b.HasOne("NetWorth.Data.Models.Account", "Account")
                        .WithMany("AccountInstruments")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetWorth.Data.Models.Instrument", "Instrument")
                        .WithMany("AccountInstruments")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountInstrumentSnapshot", b =>
                {
                    b.HasOne("NetWorth.Data.Models.AccountInstrument", "AccountInstrument")
                        .WithMany("Snapshots")
                        .HasForeignKey("AccountInstrumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NetWorth.Data.Models.AccountSnapshot", "AccountSnapshot")
                        .WithMany("InstrumentSnapshots")
                        .HasForeignKey("AccountSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccountInstrument");

                    b.Navigation("AccountSnapshot");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountSnapshot", b =>
                {
                    b.HasOne("NetWorth.Data.Models.Account", "Account")
                        .WithMany("Snapshots")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NetWorth.Data.Models.Account", b =>
                {
                    b.Navigation("AccountInstruments");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountInstrument", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("NetWorth.Data.Models.AccountSnapshot", b =>
                {
                    b.Navigation("InstrumentSnapshots");
                });

            modelBuilder.Entity("NetWorth.Data.Models.Instrument", b =>
                {
                    b.Navigation("AccountInstruments");
                });
#pragma warning restore 612, 618
        }
    }
}
