// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using net_worth_app.Data;

#nullable disable

namespace net_worth_app.Data.Migrations
{
    [DbContext(typeof(NetWorthDbContext))]
    [Migration("20260405091127_InitialNetWorthSchema")]
    partial class InitialNetWorthSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("net_worth_app.Data.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("net_worth_app.Data.Models.AccountSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("AccountSnapshots", (string)null);
                });

            modelBuilder.Entity("net_worth_app.Data.Models.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Ticker")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Name");

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("net_worth_app.Data.Models.InstrumentBalanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("AccountSnapshotId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("InstrumentBalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("net_worth_app.Data.Models.AccountSnapshot", b =>
                {
                    b.HasOne("net_worth_app.Data.Models.Account", "Account")
                        .WithMany("Snapshots")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("net_worth_app.Data.Models.Instrument", b =>
                {
                    b.HasOne("net_worth_app.Data.Models.Account", "Account")
                        .WithMany("Instruments")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("net_worth_app.Data.Models.InstrumentBalanceSnapshot", b =>
                {
                    b.HasOne("net_worth_app.Data.Models.AccountSnapshot", "AccountSnapshot")
                        .WithMany("InstrumentBalances")
                        .HasForeignKey("AccountSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("net_worth_app.Data.Models.Instrument", "Instrument")
                        .WithMany("BalanceSnapshots")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountSnapshot");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("net_worth_app.Data.Models.Account", b =>
                {
                    b.Navigation("Instruments");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("net_worth_app.Data.Models.AccountSnapshot", b =>
                {
                    b.Navigation("InstrumentBalances");
                });

            modelBuilder.Entity("net_worth_app.Data.Models.Instrument", b =>
                {
                    b.Navigation("BalanceSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
